services:
  db:
    image: mysql:${MYSQL_VERSION}
    platform: ${MYSQL_PLATFORM}
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin:${PMA_VERSION}
    restart: unless-stopped
    container_name: phpmyadmin
    platform: ${PMA_PLATFORM}
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_BLOWFISH_SECRET: ${PMA_BLOWFISH_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

volumes:
  db_data:

networks:
  db:
    driver: bridge